apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
        containers:
      - name: nginx
        image: nginx
        command:
        - /bin/sh
        - -c
        - echo 'Hello 1st version' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
