apiVersion: v1
kind: Service
metadata:
  name: nginx-service-recreate
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32100    # NodePort range: 30000-32767
